FROM python:alpine3.22

WORKDIR /app

EXPOSE 5000

# Install dependencies
RUN pip install flask
RUN pip install pymongo

# For production applications, change to a production web server
CMD ["python", "-m", "flask", "--app", "server.py", "run", "--host=0.0.0.0"]