FROM python:alpine3.22

WORKDIR /app

# Install dependencies
RUN pip install flask
RUN pip install pymongo

ENTRYPOINT [ "python" ]
# For production applications, change to a production web server
CMD ["flask run --app server.py --host=0.0.0.0"]